// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkDtiSoWUOmJXwcLvKnyJ1mak-acWRPtQ',
    appId: '1:487042716217:web:d63d96a977de15da3a73e8',
    messagingSenderId: '487042716217',
    projectId: 'fir-flutter-e6a21',
    authDomain: 'fir-flutter-e6a21.firebaseapp.com',
    storageBucket: 'fir-flutter-e6a21.firebasestorage.app',
    measurementId: 'G-M87RDK5351',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb14c3aR1iw1cV_1Z0uc9QxPkCKmDs6E0',
    appId: '1:487042716217:android:b690c105986b94bd3a73e8',
    messagingSenderId: '487042716217',
    projectId: 'fir-flutter-e6a21',
    storageBucket: 'fir-flutter-e6a21.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkDtiSoWUOmJXwcLvKnyJ1mak-acWRPtQ',
    appId: '1:487042716217:web:16efba03ffdac5d33a73e8',
    messagingSenderId: '487042716217',
    projectId: 'fir-flutter-e6a21',
    authDomain: 'fir-flutter-e6a21.firebaseapp.com',
    storageBucket: 'fir-flutter-e6a21.firebasestorage.app',
    measurementId: 'G-61NVZBPLPH',
  );
}
